{% set name = "skore" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: 35196ed84d2ffc07a59aeec8fc0c118dcc0c4b636570f01ddc7cf81e07b54ee9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - IPython
    - anywidget
    - ipywidgets
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - rich
    - scikit-learn
    - skore-local-project
    - skore-hub-project
    # Need to pin sqlite for compatibility reason with diskcache
    # cf. https://github.com/probabl-ai/skore/issues/1353
    - sqlite <3.49

test:
  imports:
    - skore
    - skore_local_project
    - skore_hub_project
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - MarieSacksick
    - sylvaincom
    - thomass-dev
    - tuscland
